version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: npm-registry-fetch
    versions:
    - 10.1.0
    - 4.0.7
    - 9.0.0
  - dependency-name: "@theholocron/jest-preset"
    versions:
    - 0.2.3
    - 0.3.0
  - dependency-name: npm
    versions:
    - 6.14.11
    - 6.14.12
    - 6.14.13
    - 7.10.0
  - dependency-name: "@theholocron/browserslist-config"
    versions:
    - 0.1.12
  - dependency-name: "@theholocron/eslint-config"
    versions:
    - 0.4.1
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: "@theholocron/storybook-config"
    versions:
    - 0.4.0
  - dependency-name: "@theholocron/semantic-release-config"
    versions:
    - 0.2.4
  - dependency-name: "@theholocron/lint-staged-config"
    versions:
    - 0.1.6
  - dependency-name: "@theholocron/webpack-config"
    versions:
    - 0.2.5
  - dependency-name: "@theholocron/markdownlint-config"
    versions:
    - 0.1.7
